name: Waka Readme

on:
  workflow_dispatch: # Supaya bisa di-run manual
  schedule:
    # Jalan otomatis setiap jam 12 malam UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Stats WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Opsi Tambahan (Boleh dihapus jika mau default):
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days # Bisa: last_7_days, last_30_days, last_6_months, last_year, all_time
          LANG_COUNT: 5 # Jumlah bahasa yang ditampilkan
          SHOW_TIME: true # Tampilkan durasi waktu
